name: iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build / Test
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.1.app/Contents/Developer
      - name: Build
        run: |
          xcodebuild build-for-testing -project Practice.xcodeproj -scheme Practice -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1'
      - name: Test
        run: |
          xcodebuild test-without-building -project Practice.xcodeproj -scheme Practice -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1'
